Controllers/OrdersController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
//using SLE_System.Models;
using System.Security.Claims;
using Kid_PalaceA2.Models;
using Kid_PalaceA2.Models.ViewModels;

using Kid_PalaceA2.Services;
using Microsoft.AspNetCore.Identity;

namespace Kid_PalaceA2.Controllers
{
    public class OrdersController : Controller
    {

        private readonly AppDbContext _db;
        private readonly ShoppingCartService _shoppingCart;
        private readonly IOrdersService _ordersService;



        public OrdersController(AppDbContext db, ShoppingCartService shoppingCart, IOrdersService ordersService)
        {
            _db = db;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                string b = User.Identity.Name.ToString();

                if ((b.Split('@')[0]) == "Admin786")
                {
                    var orderss = await _ordersService.GetOrders();
                    return View(orderss);
                }
            }

            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var orders = await _ordersService.GetOrdersByUserIdAsync(userId);
            return View(orders);
        }

        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }


        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _db.Products2.FirstOrDefaultAsync(n => n.Id == id);

            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }

            return RedirectToAction(nameof(ShoppingCart));

        }

        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _db.Products2.FirstOrDefaultAsync(n => n.Id == id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        public void AddRecievingAddress(RecievingAddress obj)
        {
            try
            {
                var items2 = _shoppingCart.GetShoppingCartItems();
                foreach (var item in items2)
                    obj.OrderId = item.Id;


                if (obj.Id == 0)
                {
                    _db.RecievingAddresses.Add(obj);
                    _db.SaveChanges();
                }
                else
                {
                    _db.Entry(obj).State = EntityState.Modified;
                    _db.SaveChanges();
                }

            }
            catch (Exception)
            {

                throw;
            }
        }


        public async Task<IActionResult> CompleteOrder(/*RegisterViewModel obj*/RecievingAddress obj)
        {

            List<RecievingAddress> list = new List<RecievingAddress>();
            list.Add(obj);
            var items = _shoppingCart.GetShoppingCartItems();

            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var items2 = list;


            if (User.Identity.IsAuthenticated)
            {
                string userEmailAddress = User.Identity.Name.ToString();

                await _ordersService.StoreOrderAsync(items, items2, userId, userEmailAddress);

            }
            //else
            //{
            //    string userEmailAddress = "";
            //    await _ordersService.StoreOrderAsync(items,items2, userId, userEmailAddress);
            //}
            //if (items.Count == 0)
            //{
            //    return View("FalseMessage");

            //}
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderStatusMessageshow");
        }


        public IActionResult CancelOrder(int Id, int status)
        {
            Order obj = new Order();
            List<Order> Orderstatuslist = new List<Order>() {
        new Order() { OrderstatusID = 1, Orderstatus = "Pending"} ,
        new Order() { OrderstatusID = 2, Orderstatus = "Processing"} ,
        new Order() { OrderstatusID = 3, Orderstatus = "Completed"} ,
        new Order() { OrderstatusID = 4, Orderstatus = "Cancelled"}
    };
            if (User.Identity.IsAuthenticated)
            {
                string b = User.Identity.Name.ToString();
                if ((b.Split('@')[0]) == "Admin786")
                {

                    var result2 = _db.Orders.SingleOrDefault(b => b.Id == Id);
                    if (result2 != null)
                    {

                        var re = Orderstatuslist.Where(s => s.OrderstatusID == status).Select(s => s.Orderstatus.ToString()).FirstOrDefault();
                        if (result2.Orderstatus == "Cancelled")
                        {
                            if (re != "Cancelled")
                            {
                                PrdquantitymanageforOther(Id);
                            }
                        }
                        if (re == "Cancelled")
                        {
                            PrdquantitymanageforCancel(Id);
                        }


                        result2.Orderstatus = re;

                        _db.SaveChanges();
                    }
                    return RedirectToAction("Index");
                }
            }
            var result = _db.Orders.SingleOrDefault(b => b.Id == Id);
            if (result != null)
            {
                result.Orderstatus = "Cancelled";
                _db.SaveChanges();
                PrdquantitymanageforCancel(Id);
            }
            return RedirectToAction("Index");

        }

        public IActionResult Changeorderstatusfordashboard(int Id, int status)
        {
            Order obj = new Order();
            List<Order> Orderstatuslist = new List<Order>() {
        new Order() { OrderstatusID = 1, Orderstatus = "Pending"} ,
        new Order() { OrderstatusID = 2, Orderstatus = "Processing"} ,
        new Order() { OrderstatusID = 3, Orderstatus = "Completed"} ,
        new Order() { OrderstatusID = 4, Orderstatus = "Cancelled"}
    };
            if (User.Identity.IsAuthenticated)
            {
                string b = User.Identity.Name.ToString();
                if ((b.Split('@')[0]) == "Admin786")
                {

                    var result2 = _db.Orders.SingleOrDefault(b => b.Id == Id);
                    if (result2 != null)
                    {

                        var re = Orderstatuslist.Where(s => s.OrderstatusID == status).Select(s => s.Orderstatus.ToString()).FirstOrDefault();
                        if (result2.Orderstatus == "Cancelled")
                        {
                            if (re != "Cancelled")
                            {
                                PrdquantitymanageforOther(Id);
                            }
                        }
                        if (re == "Cancelled")
                        {
                            PrdquantitymanageforCancel(Id);
                        }


                        result2.Orderstatus = re;

                        _db.SaveChanges();
                    }
                    return RedirectToAction("AdminDashboard", "Home");
                }
            }
            var result = _db.Orders.SingleOrDefault(b => b.Id == Id);
            if (result != null)
            {
                result.Orderstatus = "Cancelled";
                _db.SaveChanges();
                PrdquantitymanageforCancel(Id);
            }
            return RedirectToAction("AdminDashboard", "Home");

        }

        public void PrdquantitymanageforCancel(int Id)
        {
            var ordritms = _db.OrderItems.Where(x => x.OrderId == Id).ToList();

            foreach (var it in ordritms)
            {
                var prdqnty = _db.Products2.Where(x => x.Id == it.ToyModelId).ToList();
                int q = 0;
                foreach (var qnty in prdqnty)
                {
                    q = qnty.PrdQuantity + it.Quantity;
                    qnty.PrdQuantity = q;
                    _db.SaveChanges();
                }
            }
        }
        public void PrdquantitymanageforOther(int Id)
        {
            var ordritms = _db.OrderItems.Where(x => x.OrderId == Id).ToList();

            foreach (var it in ordritms)
            {
                var prdqnty = _db.Products2.Where(x => x.Id == it.ToyModelId).ToList();
                int q = 0;
                foreach (var qnty in prdqnty)
                {
                    q = qnty.PrdQuantity - it.Quantity;
                    qnty.PrdQuantity = q;
                    _db.SaveChanges();
                }
            }
        }
        public async Task<IActionResult> Orderview(int Id)
        {
            var orderss = await _ordersService.GetOrdersByOrderidAsync(Id);
            var address = await _ordersService.GetAddressByUserIdAsync(Id);

            var date = _db.Orders.Where(x => x.Id == Id).ToList();
            Orderviewdata orderviewdata = new Orderviewdata();
            foreach (var d in date)
            {
                orderviewdata.orderdate = d.Date;
            }

            orderviewdata.Address = address.ToList();
            orderviewdata.Orderr = orderss.ToList();

            return View(orderviewdata);

        }
        public IActionResult CustomerAddress()
        {

Controllers/ProductCategoryController.cs
using Kid_PalaceA2.Models;
using Kid_PalaceA2.Models.ProductM;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Kid_PalaceA2.Controllers
{
    public class ProductCategoryController : Controller
    {

        private readonly AppDbContext _db;

        public ProductCategoryController(AppDbContext db)
        {
            _db = db;
        }


        public IActionResult _Productcategory()
        {
            var a = _db.ProductCategory.ToList();
            return View(a);

        }
        public IActionResult ShowProductCategoryList()
        {
            var a = _db.ProductCategory.ToList();
            return View(a);

        }
        public IActionResult ProductCategoryCreate(ProductCatagory obj)
        {
            return View(obj);
        }

        [HttpPost]
        public IActionResult AddProductCategory(ProductCatagory obj)
        {
            try
            {
                if (obj.ProductCategoryId == 0)
                {
                    _db.ProductCategory.Add(obj);
                    _db.SaveChanges();
                }
                else
                {
                    _db.Entry(obj).State = EntityState.Modified;
                    _db.SaveChanges();
                }
                return RedirectToAction("ShowProductCategoryList");
            }
            catch (Exception)
            {

                throw;
            }

        }

        public IActionResult Delete(int id)
        {
            var obj = _db.ProductCategory.Find(id);
            if (obj != null)
            {
                _db.ProductCategory.Remove(obj);
                _db.SaveChanges();
            }
            return RedirectToAction("ShowProductCategoryList");
        }
        //public IActionResult DeleteProductCategory(int id)
        //{
        //    try
        //    {
        //        var obj = _db.ProductCategory.Find(id);
        //        if (obj != null)
        //        {
        //            _db.ProductCategory.Remove(obj);
        //            _db.SaveChangesAsync();
        //        }

        //        return RedirectToAction("ShowProductCategoryList");
        //    }
        //    catch (Exception)
        //    {

        //        throw;
        //    }
        //}

    }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kid_Palace</title>
    @*<link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />*@
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <script src="https://kit.fontawesome.com/1deb204bbf.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link href="~/css/admin.css" rel="stylesheet" />

</head>
<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar -->
        <div class="bg-white" id="sidebar-wrapper">
            <div class="sidebar-heading text-center py-4 primary-text fs-4 fw-bold text-uppercase border-bottom">
                <i class="fas fa-user-secret me-2"></i>Kid_Palace
            </div>
            <div class="list-group list-group-flush my-3">

                <a asp-area="" asp-controller="Home" asp-action="AdminDashboard" class="list-group-item list-group-item-action bg-transparent second-text active">
                    <i class="fas fa-tachometer-alt me-2"></i>Dashboard
                </a>
                <a asp-area="" asp-controller="Product" asp-action="Create" class="list-group-item list-group-item-action bg-transparent second-text fw-bold">
                    Add Products
                </a>
                <a asp-area="" asp-controller="Product" asp-action="Showtoys" class="list-group-item list-group-item-action bg-transparent second-text fw-bold">
                    ShowProducts
                </a>
                <a asp-area="" asp-controller="ProductCategory" asp-action="ProductCategoryCreate" class="list-group-item list-group-item-action bg-transparent second-text fw-bold">
                    AddNewCategory
                </a>

                <a asp-area="" asp-controller="ProductCategory" asp-action="ShowProductCategoryList" class="list-group-item list-group-item-action bg-transparent second-text fw-bold">
                    ShowProductCategory
                </a>
                <a asp-area="" asp-controller="Supplier" asp-action="SupplierCreate" class="list-group-item list-group-item-action bg-transparent second-text fw-bold">
                    AddNewSupplier
                </a>
                <a asp-area="" asp-controller="Supplier" asp-action="showSupplierDetail" class="list-group-item list-group-item-action bg-transparent second-text fw-bold">
                    ShowSuppliers
                </a>
                <a asp-area="" asp-controller="Orders" asp-action="Index" class="list-group-item list-group-item-action bg-transparent second-text fw-bold">
                    ManageAllOrders
                </a>
                <a asp-area="" asp-controller="Home" asp-action="Getusers" class="list-group-item list-group-item-action bg-transparent second-text fw-bold">
                    AllUsers
                </a>

                <partial name="_LoginPartial" />
            </div>
        </div>
        <div class="col-md-10 col-12">
            <nav class="navbar navbar-expand-lg navbar-light bg-transparent py-4 px-4">
                <div class="d-flex align-items-center">
                    <i class="fas fa-align-left primary-text fs-4 me-3" id="menu-toggle"></i>
                    <h2 class="fs-2 m-0">Dashboard</h2>
                </div>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle second-text fw-bold" href="#" id="navbarDropdown"
                               role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fas fa-user me-2"></i>Admin
                            </a>

                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    Hello @User.Identity.Name.Split('@')[0]
                                </li>
                            </ul>

                        </li>
                    </ul>
                </div>
            </nav>

            <div class="col py-3">
                <div class="container-fluid">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
            </div>
        </div>
    </div>
    <!-- navbar-->
    <!--<header class="header mb-3">
    <div id="top">
        <div class="container text-right">
            <partial name="_LoginPartial" />
        </div>-->
    <!-- *** TOP BAR END ***-->
    <!--</div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3 col-12">


                <nav class="navbar navbar-expand-lg navbar-light bg-light  bg-secondary ">
                    <div class="container-fluid ">

                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                            <div class="navbar-nav d-flex flex-column  p-5">
                                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 " id="menu">

                                    <li>
                                        <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle d-flex justify-content-start" style="margin-left:0px;">
                                            <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline fw-bold  text-black ">Products</span>
                                        </a>
                                        <ul class="collapse show nav flex-column ms-1 " id="submenu1" data-bs-parent="#menu">
                                            <li class="w-100">
                                                <a class="nav-link px-0" asp-area="" asp-controller="Product" asp-action="Create">AddToys</a>
                                            </li>
                                            <li>
                                                <a class="nav-link px-0" asp-area="" asp-controller="Product" asp-action="Showtoys">ShowToys</a>
                                            </li>
                                            <li>
                                                <a class="nav-link px-0" asp-area="" asp-controller="ProductCategory" asp-action="ProductCategoryCreate">AddCategory</a>
                                            </li>
                                            <li>
                                                <a class="nav-link px-0" asp-area="" asp-controller="ProductCategory" asp-action="ShowProductCategoryList">ShowCategory</a>
                                            </li>
                                            <li>
                                                <a class="nav-link px-0" asp-area="" asp-controller="ProdQuantity" asp-action="showProductQuantity">ShowQuantity</a>
                                                <a class="nav-link px-0" asp-area="" asp-controller="ProdQuantity" asp-action="ProductQuantityCreate">AddQuantity</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle d-flex justify-content-start">
                                            <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline text-black fw-bold ">Manage Orders</span>
                                        </a>
                                        <ul class="collapse show nav flex-column ms-1 " id="submenu1" data-bs-parent="#menu">
                                            <li class="w-100">
                                                <a class="nav-link px-0" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a>
                                            </li>

                                        </ul>
                                    </li>
                                    <li>
                                        <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle d-flex justify-content-start">
                                            <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline text-black fw-bold ">Customer Details</span>
                                        </a>
                                        <ul class="collapse show nav flex-column ms-1 " id="submenu1" data-bs-parent="#menu">
                                            <li class="w-100">
                                                <a class="nav-link px-0" asp-area="" asp-controller="Home" asp-action="Getusers">Customer</a>
                                            </li>

                                        </ul>
                                    </li>

                                </ul>
                            </div>
                        </div>
                    </div>
                </nav>
            </div>

        </div>
    </div>-->
    @*<div class="container-fluid">
            <div class="row flex-nowrap">
                <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
                    <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                        <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                            <span class="fs-5 d-none d-sm-inline">Menu</span>
                        </a>
                        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">

                            <li>
                                <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle disabled">
                                    <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline">Products</span>
                                </a>
                                <ul class="collapse show nav flex-column ms-1 " id="submenu1" data-bs-parent="#menu">
                                    <li class="w-100">
                                        <a class="nav-link px-0" asp-area="" asp-controller="Product" asp-action="Create">AddToys</a>
                                    </li>
                                    <li>
                                        <a class="nav-link px-0" asp-area="" asp-controller="Product" asp-action="Showtoys">ShowToys</a>
                                    </li>
                                    <li>
                                        <a class="nav-link px-0" asp-area="" asp-controller="ProductCategory" asp-action="ProductCategoryCreate">AddCategory</a>
                                    </li>
                                    <li>
                                        <a class="nav-link px-0" asp-area="" asp-controller="ProductCategory" asp-action="ShowProductCategoryList">ShowCategory</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle disabled">
                                    <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline">Manage Orders</span>
                                </a>
                                <ul class="collapse show nav flex-column ms-1 " id="submenu1" data-bs-parent="#menu">
                                    <li class="w-100">
                                        <a class="nav-link px-0" asp-area="" asp-controller="Orders" asp-action="Index">Orders</a>
                                    </li>

                                </ul>
                            </li>

                        </ul>

                    </div>
                </div>





        </header>
    *@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="~/js/site.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>